export enum MaterialEnum {
  Cotton = 'cotton',
  Twill = 'twill',
  Voile = 'voile',
  Linen = 'linen',
  Silk = 'silk',
  CottonSilk = 'cotton silk',
  Lyosell = 'lyosell',
  Viscose = 'viscose',
  Hemp = 'hemp',
  Mesh = 'mesh',
  Poliester = 'poliester',
  Velvet = 'velvet',
  Elastane = 'elastane',
  Canvas = 'canvas',
  Panama = 'panama',
  Crepe = 'crêpe',
  Georgette = 'georgette',
  Gabardine = 'gabardine',
  PeachSkin = 'peach skin',
  UCircular = 'u-circular',
}
